Description: >
  This template deploys an ECR repository.

Parameters:
  ProjectName:
    Description: The name of the project
    Type: String
    Default: ecs-poc

  RepositoryName:
    Description: The name of the ECR repository
    Type: String
    Default: ecs-poc

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      EncryptionConfiguration:
        EncryptionType: AES256
      Tags:
        - Key: Name
          Value: !Ref RepositoryName
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  ECRRepositoryURI:
    Description: The URL of the ECR repository
    Value: !GetAtt ECRRepository.RepositoryUri
    Export:
      Name: !Sub ${RepositoryName}-uri
