name: Infrastructure Deployment Workflow - Development

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read
    env:
      PROJECT_NAME: ecs-poc

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
          aws-region: "us-east-1"

      - name: Deploy VPC Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.PROJECT_NAME }}-vpc-stack
          template: "vpc.yaml"
          no-fail-on-empty-changeset: "1"
          disable-rollback: "1"
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: |
            EnvironmentName=dev

      - name: Deploy ECR Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.PROJECT_NAME }}-ecr-stack
          template: "ecr.yaml"
          no-fail-on-empty-changeset: "1"
          disable-rollback: "1"
          capabilities: CAPABILITY_NAMED_IAM

      - name: Deploy ECS Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ env.PROJECT_NAME }}-ecs-stack
          template: "ecs.yaml"
          no-fail-on-empty-changeset: "1"
          disable-rollback: "1"
          capabilities: CAPABILITY_NAMED_IAM
