name: Infrastructure Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
          aws-region: "us-east-1"

      - name: Deploy VPC Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "vpc-stack"
          template: "vpc.yaml"
          no-fail-on-empty-changeset: "1"
          no-delete-failed-changeset: "1"
          parameter-overrides: |
            EnvironmentName=dev

      - name: Deploy ECR Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "ecr-stack"
          template: "ecr.yaml"
          no-fail-on-empty-changeset: "1"
          no-delete-failed-changeset: "1"

      - name: Deploy ECS Cloudformation Stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: "ecs-stack"
          template: "ecs.yaml"
          no-fail-on-empty-changeset: "1"
          no-delete-failed-changeset: "1"
